### ISSUE TITLE
您好,如何让当前日期显示"今日"两个字呢?

### ISSUE THREAD

**Issue by vwo50u** [dengshiwei/CalendarView#5]
比如今天是6月15号,不显示15,而是显示"今日"

**Comment by vwo50u** [comment]
还有就是事务文字和日期文字之间的距离是怎么控制的,没有找到,在高分辨率手机上距离挺小的

**Comment by andoter0501** [comment]
https://github.com/dengshiwei/CalendarView/blob/master/src/com/dsw/datepicker/MonthDateView.java
在MonthDateView.java代码中，第115行增加判断日期号判断，如果为今天，将holiday="今天"即可。
156行有计算间距的代码。

**Comment by vwo50u** [comment]
谢谢

duruishan@yeah.net

发件人： mr_dsw
发送时间： 2016-06-16 12:28
收件人： dengshiwei/CalendarView
抄送： dursss; Author
主题： Re: [dengshiwei/CalendarView] 您好,如何让当前日期显示"今日"两个字呢? (#5)
https://github.com/dengshiwei/CalendarView/blob/master/src/com/dsw/datepicker/MonthDateView.java
在MonthDateView.java代码中，第115行增加判断日期号判断，如果为今天，将holiday="今天"即可。
156行有计算间距的代码。
