### ISSUE TITLE
请问dayAndPrice 这个的price 我传的是"",但是日期我都传了,点开还是不能选择日期

### ISSUE THREAD

**Issue by msdogo** [dengshiwei/CalendarView#6]
dayAndPrice 这个的price 我传的是"",但是日期我都传了,点开还是不能选择日期,请问哪句代码做了非空判断,找了半天没有找到...

**Comment by andoter0501** [comment]
因为当时由于项目要求，没传入price的就不让选择，具体的判断在doClickAction()方法中。可以参照下
